### ISSUE TITLE
How to get tensorflow-serving-api

### ISSUE THREAD

**Issue by patthongtra** [emacski/tensorflow-serving-arm#10]
Hi
I am using the docker image emacski/tensorflow-serving:1.15.0. How can I get tensorflow-serving-api for my application (which sends requests to tensorflow-serving)?
Thanks!

**Comment by patthongtra** [comment]
I found it - https://github.com/emacski/tensorflow-serving-arm-client 
:)

**Comment by patthongtra** [comment]
I found there is wheel version > 2.2.0
How to get version == 1.15.0 or which versions that work with tensorflow-serving version 1.15.0 ?

**Comment by emacski** [comment]
Hello,

Assuming you want to run a client on embeded arm, the short answer for versions < 2.2.0 is to use the REST API.

The [official example](https://www.tensorflow.org/tfx/serving/docker) using something like the python `requests` package:
```python
import json
import requests

r = requests.post(
    "http://localhost:8501/v1/models/half_plus_two:predict",
    data=json.dumps({"instances":[1.0, 2.0, 5.0]}))

print(r.json())
```

Otherwise, you might find someone that has fully or partially extracted the grpc client from the tensorflow and tensorflow/serving projects for those earlier versions (github.com, pypi, etc.). Even if you do find something out there, keep in mind that installation success can be spotty based on dependency coverage for your platform and may require additional modification.

**Comment by emacski** [comment]
Haven't heard back
