### ISSUE TITLE
Unexpected inference result

### ISSUE THREAD

**Issue by patthongtra** [emacski/tensorflow-serving-arm#11]
Hi,

I am using tensorflow-serving docker image 1.15.0 on Jetson Xavier with Faster RCNN for object detection. However the result from inference is incorrect (compared to tensorflow-serving docker image from tensorflow/serving on x86_64)

Do you have any ideas what can be the cause?

**Comment by emacski** [comment]
sorry, I am not sure what could be the cause off the top of my head.

If you attempt to use the emacski/tensorflow-serving x86_64 version, does it match any of the previous results? I can possibly spend a little bit of time helping to troubleshoot if you have an example model you can share that reliably reproduces the issue.

Please keep in mind: since it fits my usage pattern and to help minimize maintenance effort, this project primarily focuses on staying up to date only with the latest version of tensorflow/serving. As a result, it has been well over a year since I have looked at anything less than tensorflow 2.

**Comment by emacski** [comment]
Haven't heard back
